# Generated by Django 5.1.4 on 2025-01-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ready_to_ship',
            field=models.BooleanField(default=True, verbose_name='Ready To Ship'),
        ),
    ]
