# Generated by Django 5.1.4 on 2025-01-20 13:47

import django_resized.forms
import shop.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_number_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[300, 300], upload_to='tags/', validators=[shop.validators.FileSizeValidator(max_upload_file_size=20971520)], verbose_name='Tag'),
        ),
    ]
