# Generated by Django 5.1.4 on 2025-01-26 10:18

import shop.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='border_color',
            field=models.CharField(help_text='Border color for template (e.g., #RRGGBB or #RGB).', max_length=7, null=True, validators=[shop.validators.validate_hex_color], verbose_name='Border Color'),
        ),
    ]
