# Generated by Django 5.1.4 on 2025-02-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_color_lettersize_numbersize_remove_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lettersize',
            name='size_ar',
            field=models.CharField(max_length=50, null=True, verbose_name='Letter Size'),
        ),
        migrations.AddField(
            model_name='lettersize',
            name='size_he',
            field=models.CharField(max_length=50, null=True, verbose_name='Letter Size'),
        ),
    ]
