# Generated by Django 5.1.4 on 2025-06-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='after_sale_price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sale Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=100, verbose_name='Price'),
        ),
    ]
