# Generated by Django 5.1.4 on 2025-06-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_product_after_sale_price_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Is Featured'),
        ),
    ]
