# Generated by Django 4.2.16 on 2024-11-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_headerimage_alt_alter_headerimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_he',
            field=models.CharField(max_length=100, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='headerimage',
            name='alt_ar',
            field=models.CharField(blank=True, help_text='Text is meant to convey the “why” of the image as it relates to the content of a document or webpage', max_length=250, null=True, verbose_name='Alternative (Alt)'),
        ),
        migrations.AddField(
            model_name='headerimage',
            name='alt_en',
            field=models.CharField(blank=True, help_text='Text is meant to convey the “why” of the image as it relates to the content of a document or webpage', max_length=250, null=True, verbose_name='Alternative (Alt)'),
        ),
        migrations.AddField(
            model_name='headerimage',
            name='alt_he',
            field=models.CharField(blank=True, help_text='Text is meant to convey the “why” of the image as it relates to the content of a document or webpage', max_length=250, null=True, verbose_name='Alternative (Alt)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_he',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Product Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Product Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_he',
            field=models.CharField(max_length=255, null=True, verbose_name='Product Name'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Variant Name'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Variant Name'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='name_he',
            field=models.CharField(max_length=100, null=True, verbose_name='Variant Name'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address_he',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city_he',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description_he',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Restaurant Name'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Restaurant Name'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='name_he',
            field=models.CharField(max_length=255, null=True, verbose_name='Restaurant Name'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='state_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='state_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='state_he',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='zip_code_ar',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ZIP Code'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='zip_code_en',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ZIP Code'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='zip_code_he',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ZIP Code'),
        ),
    ]
