# Generated by Django 4.2.16 on 2024-11-15 21:11

from django.db import migrations, models
import django.db.models.deletion
import restaurant.validators


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_category_name_ar_category_name_en_category_name_he_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.ManyToManyField(related_name='products', to='restaurant.productvariant', verbose_name='Variants'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='restaurant.restaurant', verbose_name='Restaurant'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='primary_color',
            field=models.CharField(help_text='Primary color for template (e.g., #RRGGBB or #RGB).', max_length=7, null=True, validators=[restaurant.validators.validate_hex_color], verbose_name='Primary Color'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='secondary_color',
            field=models.CharField(help_text='Secondary color for template (e.g., #RRGGBB or #RGB).', max_length=7, null=True, validators=[restaurant.validators.validate_hex_color], verbose_name='Secondary Color'),
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create At')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update At')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='restaurant.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Product Type',
                'verbose_name_plural': 'Product Types',
                'ordering': ('-create_at', '-update_at'),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='types',
            field=models.ManyToManyField(related_name='types', to='restaurant.producttype', verbose_name='Types'),
        ),
    ]
