# Generated by Django 4.2.16 on 2024-11-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_remove_productvariant_product_product_variants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='name_he',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
    ]
