# Generated by Django 4.2.16 on 2024-12-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_producttype_name_ar_producttype_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='categories/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='icon',
            field=models.CharField(choices=[('🌶️', '🌶️'), ('🔥', '🔥')], max_length=20, null=True, verbose_name='Icon'),
        ),
    ]
