# Generated by Django 4.2.16 on 2024-12-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_restaurant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='secondary_color',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='theme',
            field=models.CharField(choices=[('them_1', 'Theme 1'), ('them_2', 'Theme 2'), ('them_3', 'Theme 3')], max_length=20, null=True, verbose_name='Theme'),
        ),
        migrations.AlterField(
            model_name='product',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='types', to='restaurant.producttype', verbose_name='Types'),
        ),
        migrations.AlterField(
            model_name='product',
            name='variants',
            field=models.ManyToManyField(blank=True, related_name='products', to='restaurant.productvariant', verbose_name='Variants'),
        ),
    ]
