# Generated by Django 4.2.17 on 2024-12-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_alter_restaurant_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='theme',
            field=models.CharField(choices=[('theme_1', 'Theme 1'), ('theme_2', 'Theme 2'), ('theme_3', 'Theme 3')], max_length=20, null=True, verbose_name='Theme'),
        ),
    ]
