# Generated by Django 4.2.17 on 2024-12-11 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_aboutus_theme'),
        ('restaurant', '0011_alter_restaurant_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique identifier for the restaurant used in the URL. It will be auto-generated if left blank from name.', max_length=255, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='info.theme', verbose_name='Theme'),
        ),
    ]
