# Generated by Django 4.2.17 on 2024-12-11 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_restaurant_slug_alter_restaurant_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='headerimage',
            name='alt_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='city_en',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='state_en',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='zip_code_en',
        ),
    ]
