# Generated by Django 4.2.17 on 2024-12-13 17:02

from django.db import migrations, models
import restaurant.validators


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_remove_category_name_en_remove_headerimage_alt_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(help_text='Unique identifier for the restaurant used in the URL. It must contain only English letters, numerics, dashes (-), and underscores (_)', max_length=255, unique=True, validators=[restaurant.validators.validate_english_alphanum], verbose_name='Slug'),
        ),
    ]
