# Generated by Django 4.2.17 on 2024-12-14 21:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_alter_restaurant_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='address_ar',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='address_he',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='city',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='city_ar',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='city_he',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='description',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='description_he',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='opening_time',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='state',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='state_ar',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='state_he',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='zip_code_ar',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='zip_code_he',
        ),
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('SAT', 'Saturday'), ('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3, verbose_name='Day')),
                ('is_open', models.BooleanField(default=True, help_text='Indicates whether the restaurant is open on this day', verbose_name='Open')),
                ('opening_time', models.TimeField(blank=True, default=datetime.time(9, 0), null=True, verbose_name='Opening Time')),
                ('closing_time', models.TimeField(blank=True, default=datetime.time(18, 0), null=True, verbose_name='Closing Time')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_times', to='restaurant.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Work Time',
                'verbose_name_plural': 'Work Times',
                'unique_together': {('restaurant', 'day')},
            },
        ),
    ]
