# Generated by Django 4.2.17 on 2024-12-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_remove_restaurant_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='restaurant',
        ),
        migrations.AlterField(
            model_name='producttype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='Icon'),
        ),
    ]
