# Generated by Django 4.2.17 on 2024-12-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_remove_producttype_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialink',
            name='url',
            field=models.CharField(max_length=250, null=True, verbose_name='Link / Phone Number'),
        ),
    ]
