# Generated by Django 4.2.17 on 2024-12-22 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_alter_socialmedialink_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='restaurant.restaurant', verbose_name='Restaurant'),
        ),
    ]
