# Generated by Django 4.2.17 on 2024-12-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_productvariant_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialink',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('pinterest', 'Pinterest'), ('phone_number', 'Phone Number')], max_length=20, verbose_name='Platform'),
        ),
    ]
