# Generated by Django 4.2.17 on 2024-12-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_alter_socialmedialink_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktime',
            name='is_open',
        ),
        migrations.AddField(
            model_name='worktime',
            name='is_close',
            field=models.BooleanField(default=True, help_text='Indicates whether the restaurant is close on this day', verbose_name='Close'),
        ),
    ]
