# Generated by Django 4.2.17 on 2024-12-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_remove_worktime_is_open_worktime_is_close'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='is_close',
            field=models.BooleanField(default=False, help_text='Indicates whether the restaurant is close on this day', verbose_name='Close'),
        ),
    ]
