# Generated by Django 4.2.17 on 2024-12-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_alter_worktime_is_close'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('order', '-create_at', '-update_at'), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('order', '-create_at', '-update_at'), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ('order', '-create_at', '-update_at'), 'verbose_name': 'Restaurant', 'verbose_name_plural': 'Restaurants'},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Order By'),
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Order By'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Order By'),
        ),
    ]
