# Generated by Django 4.2.17 on 2025-01-02 12:10

from django.db import migrations
import django_resized.forms
import restaurant.validators


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0023_alter_category_image_alter_headerimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[300, 300], upload_to='categories/', validators=[restaurant.validators.FileSizeValidator(max_upload_file_size=20971520)], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='headerimage',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=90, scale=None, size=[1920, 1080], upload_to='headers/', validators=[restaurant.validators.FileSizeValidator(max_upload_file_size=20971520)], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=85, scale=None, size=[600, 600], upload_to='products/', validators=[restaurant.validators.FileSizeValidator(max_upload_file_size=20971520)], verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=50, scale=None, size=[50, 50], upload_to='icons/', validators=[restaurant.validators.FileSizeValidator(max_upload_file_size=20971520)], verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[150, 150], upload_to='restaurants/', validators=[restaurant.validators.FileSizeValidator(max_upload_file_size=20971520)], verbose_name='Image'),
        ),
    ]
