# Generated by Django 4.2.17 on 2025-01-04 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0024_alter_category_image_alter_headerimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headerimage',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='headerimage',
            name='alt_ar',
        ),
        migrations.RemoveField(
            model_name='headerimage',
            name='alt_he',
        ),
        migrations.RemoveField(
            model_name='headerimage',
            name='url',
        ),
    ]
