# Generated by Django 4.2.17 on 2025-01-14 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0025_remove_headerimage_alt_remove_headerimage_alt_ar_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialmedialink',
            unique_together=set(),
        ),
    ]
