# Generated by Django 5.1.4 on 2025-01-26 10:11

import django.db.models.deletion
import django_resized.forms
import shop.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_media_links', to='info.maininfo', verbose_name='Website Main Info'),
        ),
        migrations.CreateModel(
            name='HeaderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='headers/', validators=[shop.validators.FileSizeValidator(max_upload_file_size=20971520)], verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, help_text='Setting it to false, makes the image disappear from the page', verbose_name='Active')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('info', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='header_images', to='info.maininfo', verbose_name='Website Main Info')),
            ],
            options={
                'verbose_name': 'Home Page Image',
                'verbose_name_plural': 'Home Page Images',
                'ordering': ('-create_at', '-update_at'),
            },
        ),
    ]
