# Generated by Django 5.1.4 on 2025-03-01 22:24

import django_resized.forms
import shop.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_socialmedia_info_headerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[600, 600], upload_to='about_us/', validators=[shop.validators.FileSizeValidator(max_upload_file_size=20971520)], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[300, 300], upload_to='services/', validators=[shop.validators.FileSizeValidator(max_upload_file_size=20971520)], verbose_name='Image'),
        ),
    ]
