# Generated by Django 4.2.17 on 2024-12-11 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_aboutus_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='maininfo',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='maininfo',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='title_en',
        ),
    ]
