# Generated by Django 4.2.17 on 2024-12-23 09:32

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_remove_aboutus_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=85, scale=None, size=[600, 600], upload_to='about_us/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=85, scale=None, size=[600, 300], upload_to='home/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[300, 300], upload_to='services/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=85, scale=None, size=[600, 300], upload_to='themes/', verbose_name='Image'),
        ),
    ]
