# Generated by Django 4.2.17 on 2025-01-02 12:10

from django.db import migrations
import django_resized.forms
import restaurant.validators


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_alter_aboutus_image_alter_maininfo_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=85, scale=None, size=[600, 600], upload_to='about_us/', validators=[restaurant.validators.FileSizeValidator(max_upload_file_size=20971520)], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=85, scale=None, size=[600, 300], upload_to='home/', validators=[restaurant.validators.FileSizeValidator(max_upload_file_size=20971520)], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[300, 300], upload_to='services/', validators=[restaurant.validators.FileSizeValidator(max_upload_file_size=20971520)], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=85, scale=None, size=[600, 300], upload_to='themes/', validators=[restaurant.validators.FileSizeValidator(max_upload_file_size=20971520)], verbose_name='Image'),
        ),
    ]
