# Generated by Django 4.2.17 on 2025-01-05 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_alter_aboutus_image_alter_maininfo_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='subject',
        ),
    ]
