# Generated by Django 4.2.17 on 2025-01-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_remove_contactus_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('pinterest', 'Pinterest'), ('phone_number', 'Phone Number')], max_length=20, verbose_name='Platform')),
                ('url', models.CharField(max_length=250, null=True, verbose_name='Link / Phone Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create At')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update At')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
                'ordering': ('-create_at', '-update_at'),
            },
        ),
        migrations.AddField(
            model_name='theme',
            name='url',
            field=models.URLField(null=True, verbose_name='Url'),
        ),
    ]
